[package]
name = "merkle-generator"
author = "DeGatchi"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "0.17.0", features = ["ws", "rustls", "abigen"] }
serde = "1.0.147"
serde_json = "1.0.87"
